# Generated by Django 4.0.6 on 2022-07-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef', models.CharField(max_length=500)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=100)),
                ('user_permissions', models.CharField(max_length=1000)),
                ('profile_pic', models.TextField()),
                ('nationality', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(default='no recipe name', max_length=1000)),
                ('picture', models.TextField()),
                ('recipe_description', models.CharField(default='no recipe description', max_length=1000)),
                ('ingredients', models.CharField(default='no ingredients listed', max_length=5000)),
                ('recipe', models.CharField(default='no recipe listed', max_length=10000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='onlybackend.user')),
            ],
        ),
    ]
