# Generated by Django 4.0.6 on 2022-07-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlybackend', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
