# Generated by Django 4.0.6 on 2022-07-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlybackend', '0003_alter_recipes_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
