# Generated by Django 4.0.6 on 2022-07-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlybackend', '0004_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='picture',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.TextField(),
        ),
    ]
